#!/usr/bin/env python

import sys
import urllib2
from BeautifulSoup import BeautifulSoup

if len(sys.argv) == 1:
    print 'Usage: {0} <huntgroup search>'.format(sys.argv[0])
    exit()

group = sys.argv[1].lower()
url_string = "https://finder.rackspace.net/huntgroups.php?h={0}".format(group)
req = urllib2.Request(url_string)
response = urllib2.urlopen(req)
the_page = response.read()

parsed_page = BeautifulSoup(the_page)
table = parsed_page.find('table')

data = []
try:
    rows = table.findAll('tr')
except:
    print
    print "No Huntgroups Found"
    print
    exit()

for row in rows:
    cols = row.findAll('td')
    cols = [ele.text.strip() for ele in cols]
    data.append([ele for ele in cols if ele]) # Get rid of empty values
print "{0:37}{1:47}{2:10}".format("Business Unit","Name","Number")
for i in data:
    if not i:
        continue
    print "{0:<37}{1:<47}{2:<10}".format(i[0],i[1],i[2])
