#!/usr/bin/env python
import string
import random
import sys

def pass_generator(size=6, chars=string.ascii_uppercase + string.ascii_lowercase + string.digits + '!?$&#'):
    return ''.join(random.choice(chars) for _ in range(size))

if len(sys.argv) < 2:
    print "Script takes a single integer argument."
    exit()
try:
    passlen = int(sys.argv[1])
except:
    print "Script takes a single integer argument."
    exit()
print pass_generator(passlen)
